language: python3

matrix:
  include:
      os: linux
      os: osx

install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "install osx deps" ; fi

script:
  ./bin/init_env.py --create ~/obt_staging --command obt.dep.build.all.py

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode11.3
