[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "obt"
version = "0.1.0"
description = "Orkid Build Tools (OBT)"
authors = [
    {email = "michael@tweakoz.com", name = "Michael T. Mayers"}
]
requires-python = ">=3.6"
classifiers = [
    'Programming Language :: Python :: 3.10',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent'
]
urls = {Documentation = 'https://github.com/tweakoz/ork.build/blob/develop/README.md',
        Source = 'https://github.com/tweakoz/ork.build',
        Bug Tracker = 'https://github.com/tweakoz/ork.build/issues'}

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[tool.pylint.master]
ignore = ["CVS", "bin", "lib", "local", "include"]
