from setuptools import setup, find_packages

setup(
    name="obt",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        # list of packages your package depends on
    ],
    author="Michael T. Mayers",
    author_email="michael@tweakoz.com",
    description="Orkid Build Tools (OBT)",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/tweakoz/ork.build",
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    project_urls={
        'Documentation': 'https://github.com/tweakoz/ork.build/blob/develop/README.md',
        'Source': 'https://github.com/tweakoz/ork.build',
        'Bug Tracker': 'https://github.com/tweakoz/ork.build/issues'
    }
)
