version: 2
jobs:
  build:
    docker:
      - image: tweakoz/ubuntu_builders:bionic_dev
    steps:
      - checkout
      - run: ./bin/init_env.py --create ~/obt_staging --command obt.dep.build.all.py
